[package]
name = "datacapsule-server"
version = "0.1.0"
edition = "2024"

[dependencies]
futures = "0.3.31"
r2r = "0.9.5"
serde_json = "1.0.145"
capsulelib = { package = "datacapsule-capsulelib", path = "../capsulelib" }
anyhow = "1.0.100"
log = "0.4.29"
